package com.st.tju;

//Generated by Selenium IDE
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
public class BaiduTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new FirefoxDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void untitled() {
 driver.get("https://www.baidu.com/");
 driver.manage().window().setSize(new Dimension(1098, 693));
 driver.findElement(By.id("kw")).click();
 driver.findElement(By.id("kw")).sendKeys("selenium");
 driver.findElement(By.id("su")).click();
}
}
